source 'https://rubygems.org'


gem 'rails', '4.2.4'
#gem 'rails-api'
gem 'devise'

gem 'mysql2', '~> 0.3.20'

gem 'schema_to_scaffold'

gem 'yaml_db'
gem  'composite_primary_keys'

gem 'oj'
gem 'oj_mimic_json'

gem 'html_truncator', '~>0.2'

gem 'redis'
gem 'redis-namespace'
gem 'redis-rails'
gem 'redis-rack-cache'

gem 'has_secure_token'

gem 'elasticsearch', '~> 0.4'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'

gem 'active_model_serializers', '~> 0.8.3'
gem 'rack-cors', :require => 'rack/cors'

gem 'fastimage'
#geocoder
gem 'geocoder'
#uploader
gem 'carrierwave'


gem 'mini_magick'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
