-- MySQL Script generated by MySQL Workbench
-- Mon Mar 14 17:39:30 2016
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_profile` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_profile` (
  `id_profile` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `online` TINYINT NULL DEFAULT 1,
  `date_created` DATETIME NULL COMMENT '	',
  `date_update` DATETIME NULL,
  PRIMARY KEY (`id_profile`, `id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profile_education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profile_education` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profile_education` (
  `id_profile` INT NOT NULL,
  `id_education` INT NOT NULL,
  `online` TINYINT NULL COMMENT '	',
  `ordering` INT NULL,
  PRIMARY KEY (`id_profile`, `id_education`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`education` ;

CREATE TABLE IF NOT EXISTS `mydb`.`education` (
  `id_education` INT NOT NULL AUTO_INCREMENT,
  `title` LONGTEXT NULL,
  `description` LONGTEXT NULL,
  `school` LONGTEXT NULL,
  `city` MEDIUMTEXT NULL,
  `country` MEDIUMTEXT NULL,
  `date_begin` DATETIME NULL,
  `date_end` DATETIME NULL,
  PRIMARY KEY (`id_education`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profile_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profile_skill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profile_skill` (
  `id_profile` INT NOT NULL,
  `id_skill` INT NOT NULL,
  `online` TINYINT NULL DEFAULT 1,
  `ordering` INT NULL,
  `rate` FLOAT NULL,
  PRIMARY KEY (`id_profile`, `id_skill`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`skill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`skill` (
  `id_skill` INT NOT NULL AUTO_INCREMENT,
  `id_skill_type` INT NULL,
  `title` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_skill`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`skill_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`skill_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`skill_type` (
  `id_skill_type` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NULL,
  `online` TINYINT NULL DEFAULT 1,
  `ordering` INT NULL,
  `date_created` DATETIME NULL,
  `date_updated` DATETIME NULL,
  PRIMARY KEY (`id_skill_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profile_experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profile_experience` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profile_experience` (
  `id_profile` INT NOT NULL,
  `id_experience` INT NOT NULL,
  `online` TINYINT NULL COMMENT '	',
  `ordering` INT NULL,
  PRIMARY KEY (`id_profile`, `id_experience`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`experience` ;

CREATE TABLE IF NOT EXISTS `mydb`.`experience` (
  `id_education` INT NOT NULL AUTO_INCREMENT,
  `title` LONGTEXT NULL,
  `description` LONGTEXT NULL,
  `company` LONGTEXT NULL,
  `city` MEDIUMTEXT NULL,
  `country` MEDIUMTEXT NULL,
  `date_begin` DATETIME NULL,
  `date_end` DATETIME NULL,
  PRIMARY KEY (`id_education`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profile_about`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profile_about` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profile_about` (
  `id_profile` INT NOT NULL,
  `id_about` INT NOT NULL,
  `online` TINYINT NULL DEFAULT 1,
  `ordering` INT NULL,
  PRIMARY KEY (`id_profile`, `id_about`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`about`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`about` ;

CREATE TABLE IF NOT EXISTS `mydb`.`about` (
  `id_about` INT NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NULL,
  PRIMARY KEY (`id_about`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profile_basic_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profile_basic_information` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profile_basic_information` (
  `id_profile` INT NOT NULL,
  `id_basic_information` INT NOT NULL,
  `online` TINYINT NULL DEFAULT 1,
  `ordering` INT NULL,
  PRIMARY KEY (`id_profile`, `id_basic_information`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`basic_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`basic_information` ;

CREATE TABLE IF NOT EXISTS `mydb`.`basic_information` (
  `id_basic_information` INT NOT NULL,
  `title` MEDIUMTEXT NULL,
  `looking for` MEDIUMTEXT NULL,
  `looking_where` INT NULL,
  PRIMARY KEY (`id_basic_information`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
